name: Deploy Site
on: 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Purge cache
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      # preferred
      with:
        cf_zone: ${{ secrets.CLOUDFLARE_ZONE }}
        cf_auth: ${{ secrets.CLOUDFLARE_TOKEN }}
