name: Deploy Site
on: 
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Put other steps here if you'd like, i.e. to build your site, deploy it to a service, etc.
    - name: Purge cache
      uses: Jonakemon/purge-cache-cloudflare-zone@v1.1.0
      with:
        cloudflareZone: ${{ secrets.CLOUDFLARE_ZONE }}
        cloudflareApiKey: ${{ secrets.CLOUDFLARE_TOKEN }}
